- hosts: labservers
  become: yes
  tasks:
  - name: remove httpd package
    yum:
      name: httpd
      state: absent

  - name: Remove firewalld package
    yum:
      name: firewalld
      state: absent
